# This is a basic workflow to help you get started with Actions

name: Docker Github CD (Remote SSH)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # konek ssh server
      - name: executing remote ssh commands using password
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USERNAME }} 
          key: ${{ secrets.SERVER_KEY }} 
          port: ${{ secrets.SERVER_PORT }} 
          script: |
            docker container stop chat2
            docker container rm chat2
            docker image rm aldocker01/chat-api:1.0.0
            docker pull aldocker01/chat-api:1.0.0
            docker container create --name chat2 3333:3333 aldocker01/chat-api:1.0.0
            docker container ls
            docker container start chat2
    
